### ISSUE TITLE
Mullvad VPN

### ISSUE THREAD

**Issue by baimafeima** [Devil505/solus-3rd-party-repo#5]
Thank you very much for packaging `qomui` for Solus. Would you be so kind to help package the MullvadVPN client? https://dev.getsol.us/T6793
Unfortunately, I am not a developer but this software may also be interesting for you. I need it to run a Streisand script via Solus. I would be super happy if you can help get it packaged. It has already been accepted for inclusion but unfortunately it slipped through the 30-day rule as noone stepped up to maintain it: https://dev.getsol.us/T5573
You can read about Streisand here: https://github.com/StreisandEffect/streisand

**Comment by Devil505** [comment]
Sorry I don't use github for the repo, you have to fill an issue here:
https://gitlab.com/devil505/solus-3rd-party-repo/issues

**Comment by Devil505** [comment]
I took a look, sorry but this app is builded via yarn and I don't like that, too much boring to build.
